loader:
  _target_: src.loaders.dataloader.loader
  num_workers: ${num_workers}
  batch_size: ${batch_size}
  device: ${gpus}
  extract_embeddings: ${extract_embeddings}
  concept_percentage: ${concept_percentage}
  seed: ${seed}

latent_size: ${latent_size}

# This parameter controls the equations used by the symbolic models
# If set to null, the equations will be learned from the data.
equations: null