loader:
  _target_: src.loaders.dataloader.loader
  num_workers: ${num_workers}
  batch_size: ${batch_size}
  device: ${gpus}
  extract_embeddings: ${extract_embeddings}
  concept_percentage: ${concept_percentage}

latent_size: ${latent_size}