defaults:
  - common
  - _self_

loader: 
  name: dsprites_simple
  selected_concepts: ['value_x_position', 'value_y_position']
  # Concepts available: value_shape, value_scale, value_orientation, value_x_position, value_y_position
  n_samples: 100000
  batch_size: 1024
 
  # Formulas for the dataset
  formulas: 
    circle: "exp(sin(pi * 2 * value_x_position) + cos (pi * 2 * value_y_position))"
    square: "exp(sin(pi * 2 * value_x_position) + cos (pi * 2 * value_y_position))"
    heart: "exp(sin(pi * 2 * value_x_position) + cos (pi * 2 * value_y_position))"

# Dataset parameters
metadata:
  task: regression
  lr: 0.0005
  name: dsprites_simple
  data_type: image
  concept_type: ['float', 'float'] 

# for this dataset, the equations connecting the concepts to the task are known
equations: 
  - "exp(sin(3.14 * 2 * c0) + cos(3.14 * 2 * c1))" # c0 is value_x_position, c1 is value_y_position