defaults:
  - common
  - _self_

loader: 
  name: dsprites_simple
  selected_concepts: ['value_orientation', 'value_x_position', 'value_y_position']
  n_samples: 30000
  # Concepts available: value_shape, value_scale, value_orientation, value_x_position, value_y_position
  batch_size: 512

  # Formulas for the dataset
  formulas: 
    circle: "exp(value_orientation)"
    square: "exp(value_orientation)"
    heart: "exp(value_orientation)"

# Dataset parameters
metadata:
  task: regression
  lr: 0.001
  name: dsprites
  data_type: image
  concept_type: ['float', 'float', 'float'] 

# for this dataset, the equations connecting the concepts to the task are known
equations: 
  - "exp(c0)"
  - "exp(c0)"
  - "exp(c0)"
