defaults:
  - common
  - _self_

loader: 
  name: mawps
  dataset_already_created: True

# Dataset parameters
metadata:
  task: regression
  lr: 0.001
  name: mawps
  data_type: text
  concept_type: continuous
  pretrained_transformer: invokerliang/MWP-BERT-en

equations:
  - "c0 * ( c1 + c2 )"
  - "c0 + c1 + c2"
  - "c0 + c1 - c2"
  - "( c0 + c1 ) / c2"
  - "( c0 - c1 ) / c2"
  - "c0 * ( c1 - c2 )"

# x * ( y + z )
# x + y + z
# x + y - z
# ( x + y ) / z
# ( x - y ) / z
# x * ( y - z )
