defaults:
  - common
  - _self_

loader: 
  name: mnist_arithmetic

# Dataset parameters
metadata:
  task: regression
  lr: 0.001
  name: mnist_arithmetic
  data_type: image
  concept_type: ['integer', 'integer', 'binary', 'binary', 'binary', 'binary'] 