defaults:
  - common
  - _self_

loader: 
  name: pendulum
  dataset_already_created: True
  batch_size: 1024

# Dataset parameters
metadata:
  task: regression
  lr: 0.0005
  name: pendulum
  data_type: image
  concept_type: float # Continuous concepts

# Equation to learn in pendulum dataset: 10 + 8 * sin(theta_rad) 
equations:  
  - "10 + 8 * sin(c0)"