defaults:
  - common
  - _self_

loader: 
  name: sst2

# Dataset parameters
metadata:
  task: generation
  lr: 0.001
  name: sst2
  data_type: text

latent_size: 256

encoder:
  _target_: "src.models.encoders.identity.IdentityEncoder"
  input_size: 4096
  output_size: 4096

concept_loss_form:
  _target_: "torch.nn.CrossEntropyLoss"