defaults:
  - dataset: xor
  - model: blackbox
  - engine: engine

## Common parameters
max_epochs: 500
min_epochs: 1
patience: 100
batch_size: 256
gamma: 0.5
lr_step: 100
gpus: [0]
seed: 1
activation: LeakyReLU
num_workers: 0
# this parameter can be overridden in the dataset config
latent_size: 64

## Concept-based model parameters
task_penalty: 1.0
int_prob: 0.25

hydra:
  mode: MULTIRUN
  sweeper:
    params:
      # implemented datasets: xor, dot, trigonometry, checkmark, mnist_addition, cub, celeba, (awa2), (cebab)
      dataset: nor
      # implemented models: blackbox, cbm_linear, cbm_mlp, crm, cem, dcr, licem, cmr, m_licem, v_cem, mv_cem, m_licem_pyc
      model: cbm_linear, cbm_linear_neg_weights
      seed: 2

wandb:
  project: "linear_memory_reasoner"
  entity: "gabriele-ciravegna"
note: test
