defaults:
  - dataset: xor
  - model: blackbox
  - engine: engine
  - _self_

## Common parameters
gpus: [1]
max_epochs: 500
patience: 50
lr_patience: 25
early_stopping_min_delta: 1e-3  # Minimum improvement threshold for early stopping
gamma: 0.5
seed: 1
activation: LeakyReLU
num_workers: 10

## These parameters can be overridden by the dataset config
latent_size: 64
batch_size: 128
scale_target: False

## Shared Concept-based model parameters
task_penalty: 1.0
concept_penalty: 1.0
int_prob: 0.25
hard_concepts: False
# It controls whether the concept and task predictors are trained jointly or in parallel.
disjoint_training: False

## Shared Concept-embedding based model parameters
embedding_size: 16

## Shared Concept Memory model parameters
memory_size: 10
selector_model: mlp # linear, mlp

## Pre-trained backbones
# Examples of pre-trained image backbones: resnet18, resnet34, ..., google/vit-base-patch32-224-in21k, facebook/dinov2-base
# Example of pre-trained text backbones: bert-base-uncased, ..., sentence-transformers/all-MiniLM-L6-v2
img_backbone_name: facebook/dinov2-base
text_backbone_name: sentence-transformers/all-MiniLM-L6-v2

# Parameter that controls the % of selected groups. Valid only for cub dataset. 
# Variations of this parameter will have no effect on other concepts. 
# If set to null, all groups will be selected.
concept_percentage: null

# Set this parameter to True if you want to use the stored, preprocessed dataset,
# otherwise it will be preprocessed from scratch and saved in the cache. 
use_stored_dataset: True

# Set this variable to true if you want to preprocess the data 
# using a pre-trained model.
extract_embeddings: True

wandb:
  # Set the params below if you want to use wandb as logger.
  # Set it to null if you do not want to use wandb.
  #project: null # Set to your project name
  #entity: null # Set to your wandb entity name
  entity: "francescothesantis-politecnico-di-torino"
  project: "linear_memory_reasoner"

# The note will be appended to the group name in wandb 
# and will be considered as an additional tag (for filtering).
# If you do not want to add any note, set it to null.
note: null