defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.cmr.ConceptMemoryReasoner"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: 7
  conc_rec_weight: 1.0

metadata:
  name: cmr