params:
  _target_: "src.models.crm.ConceptResidualModel"
  activation: ${activation}
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  latent_size: 128
  residual_size: 10

metadata:
  name: crm