defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.kan_sym_cbm.KANSymbolicCBM"
  task_penalty: ${task_penalty}
  concept_penalty: ${concept_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  embedding_size: ${embedding_size}
  mc_approx: 1
  speed_up_training: True

metadata:
  name: kan_symbolic_cbm