defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.lin_m_cbe.LinMCBE"
  task_penalty: ${task_penalty}
  concept_penalty: ${concept_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  embedding_size: ${embedding_size}
  mc_approx: 1
  weight_reg: ${L1_coeff}
  threshold: ${threshold}
  bias: local

metadata:
  name: lin_m_cbe