defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.m_licem.PredictCBM"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: 7
  weight_reg: 0 #1e-3
  negative_concepts: false
  hard_concepts: false
  mc_approx: 20

metadata:
  name: m_licem