defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.m_licem.PredictCBM"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: 7
  weight_reg: 0 #1e-3
  concept_state_weight: false
  use_bias: true
  mc_approx: 1

metadata:
  name: m_licem