defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.m_licem.LinearMemoryReasoner"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  negative_concepts: False
  weight_reg: 1e-4
  embedding_size: ${embedding_size}
  sampling: True
  use_bias: True
  embedding_memory: False
  intervene_on_selection: True
  linear_classifier_selection: ${linear_classifier_selection}

metadata:
  name: m_licem_no_decoder