defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.m_licem.LinearMemoryReasoner"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  memory_size: 7
  negative_concepts: True
  weight_reg: 1e-4
  embedding_size: ${embedding_size}
  sampling: false
  use_bias: false

metadata:
  name: m_licem_neg_concepts