defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.prior_sym_cbm.PriorSymbolicCBM"
  task_penalty: ${task_penalty}
  concept_penalty: ${concept_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  embedding_size: ${embedding_size}
  mc_approx: 1
  equation_learning_strategy: "prior_knowledge" 

metadata:
  name: prior_symbolic_cbm