defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.sym_m_cbe.SymMCBE"
  task_penalty: ${task_penalty}
  concept_penalty: ${concept_penalty}
  int_prob: ${int_prob}
  memory_size: ${memory_size}
  embedding_size: ${embedding_size}
  mc_approx: 1
  use_affine_parameters: False
  # Update PySR parameters as needed
  # pysr_params:
  #   niterations: 1
  #   populations: ...
  #   population_size: ...
  #   ncycles_per_iteration: ...

metadata:
  name: sym_m_cbe