defaults:
  - common
  - _self_
  
params:
  _target_: "src.models.v_cem.VariationalConceptEmbeddingModel"
  task_penalty: ${task_penalty}
  int_prob: ${int_prob}
  embedding_size: 16
  kl_penalty: 5e-2
  randint_epoch_start: 3

metadata:
  name: v_cem